---
- name: Ensure nginx configuration
  ansible.builtin.template:
    src: nginx/standalone.conf.j2
    dest: /etc/nginx/nginx.conf
  when: reverse_proxy__nginx_standalone
  notify: Restart nginx

- name: Ensure nginx configuration
  ansible.builtin.template:
    src: nginx/snippets.conf.j2
    dest: "{{ reverse_proxy__nginx_snippets_directory }}/reverse-proxy.nginx"
  when: reverse_proxy__nginx_snippets
  notify: Restart nginx

- name: Ensure Basic Auth files
  community.general.htpasswd:
    path: "/etc/nginx/conf.d/{{ item.name }}.htpasswd"
    name: "{{ item.basic_access_authentication.username }}"
    password: "{{ item.basic_access_authentication.password }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ reverse_proxy__service | flatten(levels=1) }}"
  when: "item.basic_access_authentication.enabled"
