---
# Needed for htpasswd role
- name: Ensure python passlib
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-passlib

- name: Ensure reverse proxy installation
  ansible.builtin.include_tasks: "install_{{ reverse_proxy__software }}.yaml"
