---
- name: Ensure nginx installation
  ansible.builtin.apt:
    name: nginx
    state: present
  when: reverse_proxy == "nginx"

- name: Ensure Traefik installation
  ansible.builtin.apt:
    name: traefik
    state: present
  when: reverse_proxy == "traefik"

- name: Ensure Caddy installation
  ansible.builtin.apt:
    name: caddy
    state: present
  when: reverse_proxy == "caddy"
  