---
- name: Ensure reverse proxy installation
  ansible.builtin.include_tasks: install.yaml

- name: Ensure reverse proxy configuration
  ansible.builtin.include_tasks: "configure_{{ reverse_proxy__software }}.yaml"
