---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart traefik
  service:
    name: traefik
    state: restarted

- name: restart caddy
  service:
    name: caddy
    state: restarted
